name: m360_app_corpsec
description: MEYZER360 mobile app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  app_links: ^6.3.2
  awesome_extensions: ^2.0.20
  cached_network_image: ^3.4.1
  community_charts_flutter: ^1.0.4
  country_flags: ^3.2.0
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  custom_refresh_indicator: ^4.0.1
  dart_helper_utils: ^3.3.0
  dart_jsonwebtoken: ^2.14.1
  dio: ^5.7.0
  event_bus: ^2.0.1
  firebase_core: ^3.10.0
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_helper_utils: ^3.1.0
  flutter_launcher_icons: ^0.14.2
  flutter_linkify: ^6.0.0
  flutter_native_splash: ^2.4.3
  flutter_secure_storage: 9.2.3
  fluttertoast: ^8.2.8
  geekyants_flutter_gauges: ^1.0.4
  google_fonts: ^6.2.1
  http: ^1.2.2
  jiffy: ^6.3.2
  logger: ^2.5.0
  material_table_view: ^5.0.1
  path: ^1.9.0
  path_provider: ^2.1.5
  # pdf_render: ^1.4.12
  pdfrx: ^1.1.19
  # pdfx: ^2.8.0
  photo_view: ^0.15.0
  push: ^3.3.3
  share_plus: ^10.1.4
  simple_logger: ^1.10.0
  skeletonizer: ^1.4.2
  smart_text_widget: ^0.0.3
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  table_sticky_headers: ^2.0.5
  text_scroll: ^0.2.0
  themed: ^8.0.0
  timeline_tile: ^2.0.0
  url_launcher: ^6.3.1
  local_auth: ^2.3.0
  flutter_svg: ^2.0.17

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.1
  stacked_generator: ^2.0.0-pre.1
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/img/
